repos:

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.3
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-docstring-first
      -   id: check-yaml
      -   id: no-commit-to-branch
      -   id: debug-statements
      -   id: check-merge-conflict

  -   repo: https://github.com/ambv/black
      rev: 19.3b0
      hooks:
      - id: black
        args: ["--line-length", "88"]

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.3
      hooks:
      - id: flake8
        args: ["--max-line-length=88", "--exclude=__init__.py", "--ignore=W605,W503"]

  -   repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.20
      hooks:
      -   id: isort
          args: ["-w", "88"]
