name: esmtools-dev
channels:
  - conda-forge
dependencies:
  - python=3.6
  # development
  - black
  - coveralls
  - flake8
  - importlib_metadata
  - isort
  - jupyterlab
  - nbsphinx
  - nbstripout
  - pytest
  - pytest-cov
  - sphinx
  - sphinx_rtd_theme
  - sphinx
  - sphinxcontrib-napoleon
  # IDE
  - jupyterlab
  # Input/Output
  - netcdf4
  # Miscellaneous
  - cftime
  # Numerics
  - bottleneck
  - dask
  - numpy
  - xarray
  # Package Management
  - black
  - coveralls
  - flake8
  - importlib_metadata
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-sugar
  # Statistics
  - climpred
  - scipy
  - statsmodels
  # Visualization
  - matplotlib
  - pip
  - pip:
      - pytest-tldr
