name: esmtools-dev
channels:
  - conda-forge
dependencies:
  - python=3.6
  # development
  - black
  - coveralls
  - flake8
  - importlib_metadata
  - isort
  - jupyterlab
  - nbsphinx
  - pytest
  - pytest-cov
  - sphinx
  - sphinx_rtd_theme
  # input/output
  - netcdf4
  # numerics
  - cftime
  - bottleneck
  - dask
  - numpy
  - xarray
  # stats
  - climpred
  - scipy
  - statsmodels
  # visualization
  - matplotlib
  - pip
  - pip:
      - sphinxcontrib-napoleon
      - pre-commit
