name: esmtools-dev
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - pandas
  - xarray
  - dask
  - scipy
  - matplotlib
  - bottleneck
  - netcdf4
  - pytest
  - eofs
  - cftime
  - bottleneck
  - netcdf4
  - lxml
  - climpred
  - cartopy
  - pip
  - pip:
      - xskillscore>=0.0.4
